powData <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", dec = ".", na.strings="?")

powDataRange <- subset(powData, powData$Date=="1/2/2007"|powData$Date=="2/2/2007")
powDataRange$DT <- paste(powDataRange$Date, powDataRange$Time)
powDataRange$DT <- strptime(powDataRange$DT, format = "%d/%m/%Y %H:%M:%S")               
dev.cur()
plot(powDataRange$DT, powDataRange$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering", ylim = c(0, max(powDataRange$Sub_metering_1, powDataRange$Sub_metering_2,powDataRange$Sub_metering_3)))
lines(powDataRange$DT, powDataRange$Sub_metering_2, type = "l", col = "red")
lines(powDataRange$DT, powDataRange$Sub_metering_3, type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty = 1, lwd = 2.5, col=c("black", "red", "blue"))
dev.copy(png, filename = "./plot3.png", width = 480, height = 480, units = "px", bg = "white")
dev.off()